### ISSUE TITLE
I’ve enabled the tweak but don’t see any difference even after resprings. 

### ISSUE THREAD

**Issue by Amigo1342** [midnightchip/Asteroid#10]
I thought maybe Mikoto was interfering with it, but I disabled it and I still can’t seem to get it to activate. It’s probably another tweak of some sort, but I can’t figure out which.

**Comment by Amigo1342** [comment]
Tweak list:

7-zip (POSIX): 16.02-1
Activate Link: 1.4.1-1
Activator: 1.9.13~beta2
Aerify: 1.0.6
AlarmVolume: 1.2.4
App Admin: 1.0r-101
AppList: 1.5.14
AppSync Unified: 31.1
APT (apt-key): 1.4.8-1
APT 0.7 Transitional (lib): 1:0
APT 0.7 Transitional: 1:0-1
APT 1.4 Strict (libapt-pkg): 1.4.8-3
APT Strict (lib): 1.4.8-4
APT Strict: 1.4.8-2
Assuan: 2.5.1-1
Asteroid: 1.2
Barmoji: 1.3.2
Base Structure: 1-4
Bazzi: 1.2.0
Berkeley DB: 6.2.32-1
betterFiveColumnHomescreen: 1.0.1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 4.4.23-2
bzip2: 1.0.6-1
CA Certs: 0.0.1-1
CarBridge: 1.0.2
CarPlay Lockout: 1.0
CCSupport: 1.1.2
Cephei: 1.12
ClearBadges3DTouch10: 1.0.1
ClearNotificationsOneTapPlz: 1.1.0
CocoaTop: 2.0.2-1+debug
ColorBadges: 1.2.0
ColorBanners 2: 1.1.1
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
CrashReporter: 1.16.0-1
cURL: 7.62.0-1
Cydia Installer: 1.1.32~b9
Cydia Substrate: 0.9.7000
Cydia Translations: 1.1.32~b1
Cylinder: 1.0.6
Darwin Tools: 1-6
Debian Packager: 1.18.25-5
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DismissProgress: 1.0.3
Eclipse X (iOS 11): 5.1.6
Essential: 0-1
EzCC: 1.2.4
EzLauncher: 0.0.2
Filza File Manager: 3.5.2-1
Find Utilities: 4.6.0-1
Flame: 1.3
Flipswitch: 1.0.16~beta2
FolderColor: 1.0-3
Fragment Zip Library: 28-1
FuckOffCCGrabber: 0.0.1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HapLock: 0.0.2-1
HapticKeyboard: 1.0.0
HapticPasscode: 1.0.1-2
hid-support: 1.3.1-1
HideBarX [Public]: 0.0.2
HomeHijack: 1.3.1
iCleaner Pro: 7.7.0
IconSupport: 1.11.0-1
Injector: 0.0.1
iOS Firmware: 11.3.1
iPhone Firmware (/sbin): 0-1
Kairos 2: 1.2.2
KarenLocalizer: 1.0.4
KarenPrefs: 1.4
KillBackground10 (iOS 10 & 11): 1.1.2
KSBA: 1.3.5-1
LatchKey: 1.1.1-1+debug
LetMeKnow: 1.3
libcolorpicker: 1.6-1
libcrashreport: 1.1.0-1
libCSColorPicker: 0.7.7
libCSPreferences: 1.0.4
Liberty Lite: 0.2.10
libevent: 2.1.8-2
libidn2: 6.1.2-1
libirecovery: 0.1.1+210-1
libnghttp2: 1.32.0-3
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-1
libresolv: 25-2
libSparkAppList: 1.0.0
libssh2: 1.8.0-2
libswift4: 4.2-1
libsymbolicate: 1.9.0-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
libzip: 1.5.1-1
Locale Profiles in UTF-8: 1.0-1
LockAnim: 0.0~beta4
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7
Marina: 1.0.5
mikoto: 4.0.3
MiscSettings: 2.1.0
Nettle: 3.4-2
Network Commands: 543-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm 2 (iOS 7 – 11): 2.0
NoLargeTitles: 1.1
NoLiveClock11: 0.0.1
NoMoreSmallApps [Public]: 0.0.2
NoPageDots7: 1.0
NoSlowAnimationsXI: 5.1.3-2+debug
NoSub (PalBreak w/ options): 1.3
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2q-1
OpenSSL: 1.0.2q-1
p11-kit: 0.23.12-1
PlsIgnoreAlert: 0.0.1-29
PowerModule: 1.1.1
PreferenceLoader: 2.2.4~alpha1
Profile Directory: 0-1
Push For Apollo: 0.0.1
ReachCC: 1.0.0
readline: 7.0.5-2
RocketBootstrap: 1.0.6
RomanPasscode: 2.1
Ruby: 2.5.3-2
sed: 4.5-1
shell-cmds: 118-1
shuffle: 0.8.0b
simmerDown: 1.3.1
Sleeper: 4.0.1
Snapper 2: 1.3
spawn: 0.1-1
SpotCC: 0.0.9-1+debug
StatusDND: 1.0
Substrate Safe Mode: 0.9.6001.1
Swiper: 1.0
system-cmds: 790.30.1-1
Tape Archive: 1.30-2
TapTapFlip: 1.4.2
TechSupport Framework: 1.5.0.1-1
TetherMe for iOS 8+: 1.2.2-1
TSS Checker: 263-1
TSS Saver: 1.2.0
tweakCompatible: 0.1.0
UIKit Tools: 1.1.13-4
Unc0ver Jailbreak Resources: 0.11
unloadAtd: 1.0
unloadNano: 1.0
unloadSchpa: 1.0
unloadTipsd: 1.0
unloadWbd: 1.0
unrar: 5.6.4-1
unzip: 6.0-1
UUID Generator: 1.6.2-1
WiFi Passwords: 11.0-1
XZ Utils: 5.2.4-3
zip: 2.32-1

**Comment by Amigo1342** [comment]
Yes i made sure it's enabled in all sections. I have no idea what i'm doing wrong.
________________________________

**Comment by the-casle** [comment]
Just to verify its not a compatibility thing you you try using iCleaner to disable the other tweaks (except dependencies obviously)

**Comment by Amigo1342** [comment]
Works perfectly now on iPhone X on 12.1.1 =D. Thank you!!

On Mar 5, 2019, at 13:45, the-casle <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #10<https://github.com/midnightchip/Asteroid/issues/10>.
