### ISSUE TITLE
Folder option glitches

### ISSUE THREAD

**Issue by rctfan929** [midnightchip/Asteroid#17]
When I chose trasparent folder backgrounds sometimes they won’t be.

iPhone 6s iOS 12.1.2

**Comment by rctfan929** [comment]
![047c003c-9cfa-4f77-9426-119669be0274](https://user-images.githubusercontent.com/46878212/53719765-003da080-3e2d-11e9-8cb3-47e526f3439c.png)
![e388f1eb-2270-49cf-a021-bf4194a42a00](https://user-images.githubusercontent.com/46878212/53719766-003da080-3e2d-11e9-82ea-ba802e3ccccd.png)
![e138d6e8-b9db-4b12-895c-fb772fb9960c](https://user-images.githubusercontent.com/46878212/53719768-003da080-3e2d-11e9-95ac-55974aa837af.png)
![a7080402-4c54-4aa4-b4c7-c6c1571775e1](https://user-images.githubusercontent.com/46878212/53719769-003da080-3e2d-11e9-9bf8-742c6add9775.png)

**Comment by the-casle** [comment]
I think there might be another tweak interferring. Our hide folder just hides on the lockscreen, not when actually in the folder.
