### ISSUE TITLE
Got Safe Mode

### ISSUE THREAD

**Issue by dxchien** [midnightchip/Asteroid#18]
iPhone7, iOS 12.1.1
Conflict with HomeGestureLite

**Comment by midnightchip** [comment]
Can you send me the crash log?

**Comment by dxchien** [comment]
{"blame":[],"app_name":"SpringBoard","timestamp":"2019-03-05 02:57:17.30 +0700","app_version":"1.0","slice_uuid":"695482c0-8830-348a-ab52-1a4d134a0e6c","adam_id":0,"build_version":"50","bundleID":"com.apple.springboard","share_with_app_devs":false,"is_first_party":true,"bug_type":"109","os_version":"iPhone OS 12.1.1 (16C50)","incident_id":"1DD0D123-DC79-47A5-8EBE-BBC726C59063","name":"SpringBoard","symbolicated":true}
Incident Identifier: 1DD0D123-DC79-47A5-8EBE-BBC726C59063
CrashReporter Key:   232cb7931c520efd30628d94cf8068bb3e822cb4
Hardware Model:      iPhone9,1
Process:             SpringBoard [2234]
Path:                /System/Library/CoreServices/SpringBoard.app/SpringBoard
Identifier:          com.apple.springboard
Version:             50 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.apple.springboard [63]


Date/Time:           2019-03-05 02:57:17.2937 +0700
Launch Time:         2019-03-05 02:57:14.3739 +0700
OS Version:          iPhone OS 12.1.1 (16C50)
Baseband Version:    5.30.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x00000001054db1f9   x2: 0x0000000000000002   x3: 0x00000001146f2370
    x4: 0x00000001146f2140   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000e00
    x8: 0x000001a104cf2dbd   x9: 0x000000025a2006ea  x10: 0x0000000000000d73  x11: 0x0000000268d4e08d
   x12: 0x0000000268d4e08d  x13: 0x0000000000000003  x14: 0x0000000018000000  x15: 0x000000000000001b
   x16: 0x000000022bb98828  x17: 0x00000001054dc040  x18: 0x0000000000000000  x19: 0x0000000105a86800
   x20: 0x0000000000000000  x21: 0x000000025a1e9aff  x22: 0x000000025a1ec2a6  x23: 0x00000001054de000
   x24: 0x000000025a1ee845  x25: 0x000000025a1ebcb6  x26: 0x00000001054da24d  x27: 0x00000001054da1b2
   x28: 0x000000025a1ec278   fp: 0x000000016bc1fbc0   lr: 0x00000001054d5f3c
    sp: 0x000000016bc1f9c0   pc: 0x00000001054d5f3c cpsr: 0x80000000

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef

EOF




Binary Images (dpkg):

Binary Images (App Store):

Binary Images (Other):

**Comment by the-casle** [comment]
Hey, upgrade to home gestures not home gestures lite. Lite is not being supported anymore and will be removed soon.
