### ISSUE TITLE
Notifications absent from lock screen 

### ISSUE THREAD

**Issue by haqq23** [midnightchip/Asteroid#2]
I have 'hide greeting view on notification' toggled on but when I receive a notification the screen lights up and the sound happens but nothing appears on the screen. Thanks for your work on this!!

**Comment by midnightchip** [comment]
We've just noticed this bug, and will do our best to fix it within the next day. Currently the fix is to just respring, or lock and unlock your screen a couple times

**Comment by haqq23** [comment]
thanks I really appreciate it, it looks great so far.
