### ISSUE TITLE
TR Language Translation

### ISSUE THREAD

**Issue by ulasates** [midnightchip/Asteroid#22]
Hey! I'm UlasAtes from Reddit. I translated preferences/resources/base.lproj to Turkish. I hope you will like and add support for TR. :) 

[Asteroid-TR.zip](https://github.com/midnightchip/Asteroid/files/2926874/Asteroid-TR.zip)

**Comment by midnightchip** [comment]
Merged, thanks!

**Comment by ulasates** [comment]
Hey! I missed the lockscreen greeting texts, sorry. I added lockWeather.bundle/Localizable.strings in Turkish. Thanks for your work! If anything other than these needed, let me know :)

[Localizable.strings.zip](https://github.com/midnightchip/Asteroid/files/2927975/Localizable.strings.zip)

**Comment by ulasates** [comment]
@midnightchip

**Comment by the-casle** [comment]
We got it
