### ISSUE TITLE
Could you move the hourly forecast a little bit higher?

### ISSUE THREAD

**Issue by vitorkrau** [midnightchip/Asteroid#31]
Could u add an option for us to set the hourly forecast height? It will be awesome to have this at the same height of a notification and dismiss when a real notification comes up.

THX

**Comment by the-casle** [comment]
It can be resized, I'm not sure how it would it would format if users could change height. If you enable the hide when notifications present in preferences it should get that result

**Comment by vitorkrau** [comment]
The dismiss feature I know and I use it and I also know that let users change the height would be difficult to format because of the clock but if u can add a preset to have this at the same height of notifications. One preset for the original height and one a little bit higher than the original. I can send a photo to show what I mean.

**Comment by vitorkrau** [comment]
I just saw the photoshop with a forecast here on github and I guess mine has a problem. I'll upload a photo and if u can verify this for me, I'll be glad.

**Comment by vitorkrau** [comment]
![a327f46b-4055-44eb-9b4a-709ad36de7bd](https://user-images.githubusercontent.com/17788762/53775269-a8f10c00-3ed0-11e9-904f-acb36d2b59a9.jpg)

**Comment by the-casle** [comment]
If you enter editing mode it can be shrunk.

**Comment by vitorkrau** [comment]
Done. Thanks for this and for your great work!
