### ISSUE TITLE
Lockscreen has plain animation not the one I choose 

### ISSUE THREAD

**Issue by jonathanpartida10** [midnightchip/Asteroid#32]
I choose a weather theme but when my phone respringed the theme shown was just a plain one with clouds moving slowly and just somewhat night time. How can I fix this so it shows the one I choose for the lockscreen? I choose the server thunderstorm.

**Comment by the-casle** [comment]
Manual condition codes are being worked on.

**Comment by jonathanpartida10** [comment]
thank you,please keep me updated :)
