### ISSUE TITLE
Lock screen movement

### ISSUE THREAD

**Issue by callmechknnugz** [midnightchip/Asteroid#33]
Whenever my phone raises to wake and I have my finger on the screen (which is always because I’m a female and pockets literally don’t exist on our clothes) it puts it in wiggle mode and moves the contents all over the screen. Making me to have to go to the lock screen settings and reset the positioning, resprining my device. 
I can’t find an option to completely disable this. 
This is an issue, and needs to be fixed. 
If there is an option to do so, please show me.

**Comment by the-casle** [comment]
Ill make a switch in preferences to disable editing mode. I’ll need to throw in a little shake animation or something if try to edit when disabled so people know its not just broken.

**Comment by callmechknnugz** [comment]
You’re a legend
