### ISSUE TITLE
Can’t hide the live weather background for thunderstorms

### ISSUE THREAD

**Issue by user682** [midnightchip/Asteroid#49]
The live weather background is still there even when it’s disabled. Seems to only happens by any of the different thunderstorms conditions. Expect "ScatteredThunderstorms".

**Comment by the-casle** [comment]
It looks like the entire background is being animated. The clouds would have to be removed entirely for that to work.

**Comment by user682** [comment]
When only the clouds have to removed, it wouldn’t be really bad because the heavy rain and lightning effects alone are still awesome. I would really appreciate it if it can be added to work without the background even when there are no clouds tho.
