### ISSUE TITLE
Animations frozen?

### ISSUE THREAD

**Issue by boyooo** [midnightchip/Asteroid#50]
I’ve restored my phone, i’ve unintsalled the tweak . nothing seems to make the animations actually moves.... is there a fix for this ? please help me!

**Comment by boyooo** [comment]
Okay!!!! Reduce motion stops everything from moving! (facepalm)

**Comment by the-casle** [comment]
Interesting, Ill leave this open so I remember to create an alert for users with reduce motion.

**Comment by daynight91** [comment]
Hello, I disabled “reduced motion”. All works perfect except animations. (Using IPad 6)
