### ISSUE TITLE
Lockscreen Glitch text overlaps

### ISSUE THREAD

**Issue by Iam2smart** [midnightchip/Asteroid#53]
There is a bug on the lockscreen when there is a ton of text it over laps itself. iPod Touch 6 iOS 11.4

![F72ED677-1B5A-41B8-8884-598B11FF9EBE](https://user-images.githubusercontent.com/25376595/54089342-9857f000-432d-11e9-85b5-3f0ab22a2b76.png)

**Comment by the-casle** [comment]
You can move it through editing mode and resize it. There’s also smaller text sizes in preferences.
