### ISSUE TITLE
iPad support would be cool

### ISSUE THREAD

**Issue by VXkiller85** [midnightchip/Asteroid#63]
![A7569BF2-4A03-4FAF-82C7-7E968EF8A227](https://user-images.githubusercontent.com/44416159/56009664-9a0b2f80-5cae-11e9-87fe-aec3a12df453.png)
I think the image explains it but I can’t ajust it.

**Comment by the-casle** [comment]
Yep, I already fixed the rotation and it will be released pretty soon
