### ISSUE TITLE
Notifications not showing up

### ISSUE THREAD

**Issue by cjmk75** [midnightchip/Asteroid#68]
iPhone X iOS 12.2.1
When I enable this tweak my phone still buzzes when I get any type of notification but no banner is showing up on lock screen. Soon as I disable this tweak the issue is fixed. I have tried respring, reboot, iCleaner etc with no luck. The only reason I can think may be possibly causing this is a compatibility issue with the tweak Notifca that I have installed that colours my banners.

**Comment by the-casle** [comment]
Wait ios 10.2.1? I didnt even think it was compatible with ios 10.

**Comment by cjmk75** [comment]
God damn it I’m sorry I meant 12.1.2

**Comment by the-casle** [comment]
lol its fine. I think we fixed the disappearing notifications a bit ago but they might have popped back up. What uncover version are you on?

**Comment by cjmk75** [comment]
2.0.1

**Comment by the-casle** [comment]
uncover, like jailbreak version

**Comment by cjmk75** [comment]
Ah my bad, uncover b50

**Comment by the-casle** [comment]
ugh why did uncover b50 break so much stuff

**Comment by the-casle** [comment]
This is the second report of b50 messing up something in Asteroid

**Comment by cjmk75** [comment]
Ah rip, If you need any testing done to fix this I could help you

**Comment by the-casle** [comment]
What preference switches do you have enabled to cause the issue? AlsoI can send our most recent deb to see if it fixes anything

**Comment by the-casle** [comment]
https://www.dropbox.com/s/t3fnewtob6cckoa/com.thecasle.astsetup_0.0.4_iphoneos-arm.deb?dl=0
Install first ^
https://www.dropbox.com/s/9s9acfcjpn0i632/com.midnightchips.asteroid_2.0.5-669_iphoneos-arm.deb?dl=0

**Comment by cjmk75** [comment]
On uncover?

Load tweaks
Load daemons
Dump ApTicket
Disiable Auto Updates
Disable app revokes
Overwrite boot nonce 
Reload system daemons

**Comment by cjmk75** [comment]
And in asteroid only current temperature and glyph

**Comment by cjmk75** [comment]
I’ll give the new deb a try now

**Comment by cjmk75** [comment]
Installed the new deb and it functions as normal except notifications still aren’t showing :/

**Comment by the-casle** [comment]
Ok, well I’ll try to figure it out. Does the problem still happen when you disable all other tweaks

**Comment by the-casle** [comment]
Also if you swipe up on the lockscreen does it show the notifications? The notifications are hidden when the greeting is revealed and maybe its formatting off screen or something.

**Comment by cjmk75** [comment]
Well it’s an iPhone X, if I swipe up on the lock screen it just unlocks the phone and I don’t see any animation of the notifications when unlocking it

**Comment by cjmk75** [comment]
Unless you mean opening Notification Center then yes they appear then

**Comment by cjmk75** [comment]
After doing a little more testing with it I realized that if you just barely swipe up around the middle of the screen but not enough to open Notification Center then your current Notifications will appear! However if you lock your phone again and turn it back on then they’re no longer there.

**Comment by the-casle** [comment]
Well yea thats the lockscreen greeting, if you turn on the blur and maybe a couple other things it will be more apparent

**Comment by zocchi21** [comment]
Are we able to have notifications appear on lock screen along with Greeting View? I'd like to see Greeting View at the top of my screen and notifications below it without having to swipe up to see notifications. I currently have Enable Greeting View turned on and Hide Greeting View on Notification turned off.

Not sure if this is already possible via some other setting or if this is an enhancement request. Thanks for a great tweak!
