### ISSUE TITLE
German "Good Afternoon" translate

### ISSUE THREAD

**Issue by Xador123** [midnightchip/Asteroid#69]
Hello, fantastic update from Asteroid, everything is going very well so far. Unfortunately, in the german welcome text for the day is a false translation. "Good Afternoon" doesn't exist. "Good Afternoon  = " Guten Tag"   thank you, great Tweak

**Comment by the-casle** [comment]
Will get it fixed thanks!

**Comment by Xador123** [comment]
Thanks now it fits, PayPAl also works:-)
