### ISSUE TITLE
Iphone XR When Install 

### ISSUE THREAD

**Issue by shifazsittu123** [midnightchip/Asteroid#76]
When install on XR it got Stuck in lock Screen i have to Power off & Remove Tweak after Dissable Tweak & Jailbreak

**Comment by the-casle** [comment]
Thank you, we are aware and working on figuring it out

**Comment by H7777x** [comment]
Thx

**Comment by H7777x** [comment]
Tt

**Comment by H7777x** [comment]
Ttttt

**Comment by the-casle** [comment]
Found the respring loop. Cleaning up a couple more bugs and then I'll get an update out
