### ISSUE TITLE
Settings App Crashes

### ISSUE THREAD

**Issue by ShutNSmoq** [midnightchip/Asteroid#78]
Settings app crashes when you try to open it but if you enable your cellular data you can open it and it is annoying
Note: I added your repo to cydia

**Comment by ShutNSmoq** [comment]
Fixed it

**Comment by the-casle** [comment]
Did you just update libcspreferences?

**Comment by bonzozo971** [comment]
hello i have the same problem how did you fix it please 😁🙏🙏🙏

**Comment by ShutNSmoq** [comment]
Its because of another tweak called gestro or something like that

**Comment by bonzozo971** [comment]
merci

**Comment by the-casle** [comment]
Dang gesto crashing everyone lol

**Comment by ShutNSmoq** [comment]
XD
