### ISSUE TITLE
Screen response delayed and buttons too

### ISSUE THREAD

**Issue by Commish708** [midnightchip/Asteroid#82]
I discovered this issue today. I have an iPhone x on 11.3.1. When my phone has no cellular signal and not on wifi, the screen touch/animation will be slow to respond. The volume buttons will also have a delay as well. It can be so slow that the phone becomes unusable and I need to go into safemode. Sometimes it will freeze and take a few seconds delayed to respond to the screen touches. You can replicate this issue by putting your phone in airplane mode with no wifi connection and respring. My screen gets slow every time. Connecting back to cellular or wifi and springing, brings the phone back to normal. If I disable Asteroid and turn on airplane mode with no wifi, there's no issues. If you always have a connection with wifi or cellular, you may never encounter this issue.

**Comment by the-casle** [comment]
Having issues when it can't get the weather. For example if you respring in airplane I believe it would respring loop. It's hard to trace down but I'm working hard to find it
