### ISSUE TITLE
Can’t dismiss greeting when XenHTML is installed

### ISSUE THREAD

**Issue by Garlicvideos** [midnightchip/Asteroid#86]
When XenHTML is enabled, it’s layers prevents the greetings menu from being dismissed.

I tested this multiple times and it’s easily replicable. Literally unplayable. Valve, please fix.

**Comment by the-casle** [comment]
Yea Idk if I can fix that. I believe most users just disabled xenhtml on the lockscreen... Its more of a conflict than a bug

**Comment by Garlicvideos** [comment]
Ah ok. Is there any other way you’d recommend getting the discharge text onto the lockscreen?

**Comment by the-casle** [comment]
No sorry.
